### ISSUE TITLE
[Feat] 오픈소스 라이브러리 사용 고지

### ISSUE THREAD

**Issue by HI-JIN2** [EAT-SSU/Android#242]
## 목적

> 오픈소스 라이브러리 사용 고지

## 참고사항
- https://developers.google.com/android/guides/opensource?hl=ko
- https://junyoeng.tistory.com/entry/Android-Open-Source-Library-%ED%91%9C%EC%8B%9C%ED%95%98%EA%B8%B0

**Comment by HI-JIN2** [comment]
다른 방법도 있음
- https://github.com/jaredsburrows/gradle-license-plugin

**Comment by YUNSO99** [comment]
신기하네요 저는 현재 적용하신 방식이 더 좋아보입니다!!
